[package]
name = "subsystem-demographics"
version.workspace = true
edition.workspace = true

[dependencies]
sim-equations = { path = "../sim-equations" }
sim-types = { path = "../sim-types" }
sim-contracts = { path = "../sim-contracts" }
sim-state = { path = "../sim-state" }

[lib]
path = "src/lib.rs"