[package]
name = "sim-tools"
version.workspace = true
edition.workspace = true

[dependencies]
subsystem-energy = { path = "../subsystem-energy" }
sim-registry = { path = "../sim-registry" }
sim-kernel = { path = "../sim-kernel" }
sim-state = { path = "../sim-state" }

[[bin]]
name = "sim-tools"
path = "src/main.rs"